gui2: Prevent "control reaches end of non-void function" warning on gcc 4.7
This is a quick fix and mordante should review it later.

gcc 4.7 doesn't seem to be happy with gui2::tplacer_::build()'s switch
statement and appears to expect more cases despite
gui2::tplacer_::tgrow_direction doesn't have more members. The warning
in question:

  src/gui/auxiliary/placer.cpp:43:1: error: control reaches end of non-void function [-Werror=return-type]

git-svn-id: http://svn.gna.org/svn/wesnoth/trunk@54244 75b3775d-3801-0410-9e12-e2e43121521d